/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'
import { Route as DashboardManagerRouteImport } from './routes/dashboard/manager'
import { Route as DashboardDevRouteImport } from './routes/dashboard/dev'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as ProjectsIdTasksRouteImport } from './routes/projects/$id/tasks'
import { Route as ProjectsIdScheduleRouteImport } from './routes/projects/$id/schedule'
import { Route as ProjectsIdEditRouteImport } from './routes/projects/$id/edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardManagerRoute = DashboardManagerRouteImport.update({
  id: '/dashboard/manager',
  path: '/dashboard/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDevRoute = DashboardDevRouteImport.update({
  id: '/dashboard/dev',
  path: '/dashboard/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdTasksRoute = ProjectsIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdScheduleRoute = ProjectsIdScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdEditRoute = ProjectsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProjectsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/dev': typeof DashboardDevRoute
  '/dashboard/manager': typeof DashboardManagerRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projects/$id/schedule': typeof ProjectsIdScheduleRoute
  '/projects/$id/tasks': typeof ProjectsIdTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/dev': typeof DashboardDevRoute
  '/dashboard/manager': typeof DashboardManagerRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projects/$id/schedule': typeof ProjectsIdScheduleRoute
  '/projects/$id/tasks': typeof ProjectsIdTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/dev': typeof DashboardDevRoute
  '/dashboard/manager': typeof DashboardManagerRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projects/$id/schedule': typeof ProjectsIdScheduleRoute
  '/projects/$id/tasks': typeof ProjectsIdTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/dev'
    | '/dashboard/manager'
    | '/projects/$id'
    | '/projects/$slug'
    | '/projects/new'
    | '/projects'
    | '/projects/$id/edit'
    | '/projects/$id/schedule'
    | '/projects/$id/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/dev'
    | '/dashboard/manager'
    | '/projects/$id'
    | '/projects/$slug'
    | '/projects/new'
    | '/projects'
    | '/projects/$id/edit'
    | '/projects/$id/schedule'
    | '/projects/$id/tasks'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/privacy'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/dev'
    | '/dashboard/manager'
    | '/projects/$id'
    | '/projects/$slug'
    | '/projects/new'
    | '/projects/'
    | '/projects/$id/edit'
    | '/projects/$id/schedule'
    | '/projects/$id/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  DashboardDevRoute: typeof DashboardDevRoute
  DashboardManagerRoute: typeof DashboardManagerRoute
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/manager': {
      id: '/dashboard/manager'
      path: '/dashboard/manager'
      fullPath: '/dashboard/manager'
      preLoaderRoute: typeof DashboardManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/dev': {
      id: '/dashboard/dev'
      path: '/dashboard/dev'
      fullPath: '/dashboard/dev'
      preLoaderRoute: typeof DashboardDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/tasks': {
      id: '/projects/$id/tasks'
      path: '/tasks'
      fullPath: '/projects/$id/tasks'
      preLoaderRoute: typeof ProjectsIdTasksRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/schedule': {
      id: '/projects/$id/schedule'
      path: '/schedule'
      fullPath: '/projects/$id/schedule'
      preLoaderRoute: typeof ProjectsIdScheduleRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/edit': {
      id: '/projects/$id/edit'
      path: '/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof ProjectsIdEditRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
  }
}

interface ProjectsIdRouteChildren {
  ProjectsIdEditRoute: typeof ProjectsIdEditRoute
  ProjectsIdScheduleRoute: typeof ProjectsIdScheduleRoute
  ProjectsIdTasksRoute: typeof ProjectsIdTasksRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdEditRoute: ProjectsIdEditRoute,
  ProjectsIdScheduleRoute: ProjectsIdScheduleRoute,
  ProjectsIdTasksRoute: ProjectsIdTasksRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  DashboardDevRoute: DashboardDevRoute,
  DashboardManagerRoute: DashboardManagerRoute,
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
